using System;

namespace DevX.WindowsService.Win32
{
    [Flags]
    internal enum SC_MANAGER_ACCESS
    {
        SC_MANAGER_CONNECT = 0x0001,
        SC_MANAGER_CREATE_SERVICE = 0x0002,
        SC_MANAGER_ENUMERATE_SERVICE = 0x0004,
        SC_MANAGER_LOCK = 0x0008,
        SC_MANAGER_MODIFY_BOOT_CONFIG = 0x0020,
        SC_MANAGER_QUERY_LOCK_STATUS = 0x0010,
        SC_MANAGER_ALL_ACCESS =
            ACCESS.STANDARD_RIGHTS_REQUIRED |
            SC_MANAGER_CONNECT |
            SC_MANAGER_CREATE_SERVICE |
            SC_MANAGER_ENUMERATE_SERVICE |
            SC_MANAGER_LOCK |
            SC_MANAGER_QUERY_LOCK_STATUS |
            SC_MANAGER_MODIFY_BOOT_CONFIG,

        GENERIC_READ =
            ACCESS.STANDARD_RIGHTS_READ |
            SC_MANAGER_ENUMERATE_SERVICE |
            SC_MANAGER_QUERY_LOCK_STATUS,
        GENERIC_WRITE =
            ACCESS.STANDARD_RIGHTS_WRITE |
            SC_MANAGER_CREATE_SERVICE |
            SC_MANAGER_MODIFY_BOOT_CONFIG,
        GENERIC_EXECUTE =
            ACCESS.STANDARD_RIGHTS_EXECUTE |
            SC_MANAGER_CONNECT |
            SC_MANAGER_LOCK,
        GENERIC_ALL = SC_MANAGER_ALL_ACCESS,
    }
}
