using System;

namespace DevX.WindowsService.Win32
{
    [Flags]
    internal enum SERVICE_ACCESS
    {
        SERVICE_QUERY_CONFIG = 0x0001,
        SERVICE_CHANGE_CONFIG = 0x0002,
        SERVICE_QUERY_STATUS = 0x0004,
        SERVICE_ENUMERATE_DEPENDENTS = 0x0008,
        SERVICE_START = 0x0010,
        SERVICE_STOP = 0x0020,
        SERVICE_PAUSE_CONTINUE = 0x0040,
        SERVICE_INTERROGATE = 0x0080,
        SERVICE_USER_DEFINED_CONTROL = 0x0100,
        SERVICE_ALL_ACCESS =
            ACCESS.STANDARD_RIGHTS_REQUIRED |
            SERVICE_QUERY_CONFIG |
            SERVICE_CHANGE_CONFIG |
            SERVICE_QUERY_STATUS |
            SERVICE_ENUMERATE_DEPENDENTS |
            SERVICE_START |
            SERVICE_STOP |
            SERVICE_PAUSE_CONTINUE |
            SERVICE_INTERROGATE |
            SERVICE_USER_DEFINED_CONTROL,

        DELETE = ACCESS.DELETE,
        READ_CONTROL = ACCESS.READ_CONTROL,
        WRITE_DAC = ACCESS.WRITE_DAC,
        WRITE_OWNER = ACCESS.WRITE_OWNER,

        GENERIC_READ =
            ACCESS.STANDARD_RIGHTS_READ |
            SERVICE_QUERY_CONFIG |
            SERVICE_QUERY_STATUS |
            SERVICE_INTERROGATE |
            SERVICE_ENUMERATE_DEPENDENTS,
        GENERIC_WRITE =
            ACCESS.STANDARD_RIGHTS_WRITE |
            SERVICE_CHANGE_CONFIG,
        GENERIC_EXECUTE =
            ACCESS.STANDARD_RIGHTS_EXECUTE |
            SERVICE_START |
            SERVICE_STOP |
            SERVICE_PAUSE_CONTINUE |
            SERVICE_USER_DEFINED_CONTROL,
    }
}
